name: auth01

services:
  products:
    build: 
      context: ./user-management
      dockerfile: Dockerfile
    volumes:
      - ./user-management:/code
    ports:
      - "8085:8085"

  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=hubaib_mehmood
      - POSTGRES_PASSWORD=user_db_management
      - POSTGRES_DB=user_db
    ports:
        - '5433:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
networks:
  default:
    driver: bridge
